//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: player.proto
namespace dhc
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_t")]
  public partial class player_t : global::ProtoBuf.IExtensible
  {
    public player_t() {}
    
    private ulong _guid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _serverid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int serverid
    {
      get { return _serverid; }
      set { _serverid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _region_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"region_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int region_id
    {
      get { return _region_id; }
      set { _region_id = value; }
    }
    private string _infomation = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"infomation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string infomation
    {
      get { return _infomation; }
      set { _infomation = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private ulong _birth_time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"birth_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong birth_time
    {
      get { return _birth_time; }
      set { _birth_time = value; }
    }
    private ulong _last_daily_time = default(ulong);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"last_daily_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_daily_time
    {
      get { return _last_daily_time; }
      set { _last_daily_time = value; }
    }
    private ulong _last_week_time = default(ulong);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"last_week_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_week_time
    {
      get { return _last_week_time; }
      set { _last_week_time = value; }
    }
    private ulong _last_month_time = default(ulong);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"last_month_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_month_time
    {
      get { return _last_month_time; }
      set { _last_month_time = value; }
    }
    private ulong _last_login_time = default(ulong);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"last_login_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_login_time
    {
      get { return _last_login_time; }
      set { _last_login_time = value; }
    }
    private ulong _last_check_time = default(ulong);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"last_check_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong last_check_time
    {
      get { return _last_check_time; }
      set { _last_check_time = value; }
    }
    private int _is_guide = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"is_guide", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int is_guide
    {
      get { return _is_guide; }
      set { _is_guide = value; }
    }
    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _jewel = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"jewel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int jewel
    {
      get { return _jewel; }
      set { _jewel = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private int _exp = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private int _cup = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cup
    {
      get { return _cup; }
      set { _cup = value; }
    }
    private int _snow = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"snow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int snow
    {
      get { return _snow; }
      set { _snow = value; }
    }
    private int _battle_gold = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"battle_gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battle_gold
    {
      get { return _battle_gold; }
      set { _battle_gold = value; }
    }
    private int _max_cup = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"max_cup", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_cup
    {
      get { return _max_cup; }
      set { _max_cup = value; }
    }
    private int _max_score = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"max_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_score
    {
      get { return _max_score; }
      set { _max_score = value; }
    }
    private int _max_sha = default(int);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"max_sha", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_sha
    {
      get { return _max_sha; }
      set { _max_sha = value; }
    }
    private int _max_lsha = default(int);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"max_lsha", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_lsha
    {
      get { return _max_lsha; }
      set { _max_lsha = value; }
    }
    private int _box_zd_num = default(int);
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"box_zd_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int box_zd_num
    {
      get { return _box_zd_num; }
      set { _box_zd_num = value; }
    }
    private int _box_zd_opened = default(int);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"box_zd_opened", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int box_zd_opened
    {
      get { return _box_zd_opened; }
      set { _box_zd_opened = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _box_ids = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(52, Name=@"box_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> box_ids
    {
      get { return _box_ids; }
    }
  
    private int _box_open_slot = default(int);
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"box_open_slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int box_open_slot
    {
      get { return _box_open_slot; }
      set { _box_open_slot = value; }
    }
    private ulong _box_open_time = default(ulong);
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"box_open_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong box_open_time
    {
      get { return _box_open_time; }
      set { _box_open_time = value; }
    }
    private ulong _sign_time = default(ulong);
    [global::ProtoBuf.ProtoMember(55, IsRequired = false, Name=@"sign_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong sign_time
    {
      get { return _sign_time; }
      set { _sign_time = value; }
    }
    private int _sign_index = default(int);
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"sign_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sign_index
    {
      get { return _sign_index; }
      set { _sign_index = value; }
    }
    private int _sign_finish = default(int);
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"sign_finish", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sign_finish
    {
      get { return _sign_finish; }
      set { _sign_finish = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _role_guid = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(100, Name=@"role_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> role_guid
    {
      get { return _role_guid; }
    }
  
    private ulong _role_on = default(ulong);
    [global::ProtoBuf.ProtoMember(101, IsRequired = false, Name=@"role_on", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong role_on
    {
      get { return _role_on; }
      set { _role_on = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _item_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(102, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> item_id
    {
      get { return _item_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _item_num = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(103, Name=@"item_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> item_num
    {
      get { return _item_num; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _avatar = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(104, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> avatar
    {
      get { return _avatar; }
    }
  
    private int _avatar_on = default(int);
    [global::ProtoBuf.ProtoMember(106, IsRequired = false, Name=@"avatar_on", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int avatar_on
    {
      get { return _avatar_on; }
      set { _avatar_on = value; }
    }
    private readonly global::System.Collections.Generic.List<ulong> _battle_his_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(107, Name=@"battle_his_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> battle_his_guids
    {
      get { return _battle_his_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _post_guids = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(109, Name=@"post_guids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> post_guids
    {
      get { return _post_guids; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _achieve_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(110, Name=@"achieve_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> achieve_id
    {
      get { return _achieve_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _achieve_num = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(111, Name=@"achieve_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> achieve_num
    {
      get { return _achieve_num; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _achieve_reward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(112, Name=@"achieve_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> achieve_reward
    {
      get { return _achieve_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _achieve_time = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(113, Name=@"achieve_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> achieve_time
    {
      get { return _achieve_time; }
    }
  
    private int _achieve_point = default(int);
    [global::ProtoBuf.ProtoMember(114, IsRequired = false, Name=@"achieve_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieve_point
    {
      get { return _achieve_point; }
      set { _achieve_point = value; }
    }
    private int _achieve_index = default(int);
    [global::ProtoBuf.ProtoMember(115, IsRequired = false, Name=@"achieve_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieve_index
    {
      get { return _achieve_index; }
      set { _achieve_index = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _toukuang = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(116, Name=@"toukuang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> toukuang
    {
      get { return _toukuang; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _toukuang_time = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(117, Name=@"toukuang_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> toukuang_time
    {
      get { return _toukuang_time; }
    }
  
    private int _toukuang_on = default(int);
    [global::ProtoBuf.ProtoMember(118, IsRequired = false, Name=@"toukuang_on", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int toukuang_on
    {
      get { return _toukuang_on; }
      set { _toukuang_on = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _task_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(119, Name=@"task_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> task_id
    {
      get { return _task_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _task_num = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(120, Name=@"task_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> task_num
    {
      get { return _task_num; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _task_reward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(121, Name=@"task_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> task_reward
    {
      get { return _task_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _fashion_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(122, Name=@"fashion_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fashion_id
    {
      get { return _fashion_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _fashion_on = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(123, Name=@"fashion_on", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> fashion_on
    {
      get { return _fashion_on; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _daily_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(124, Name=@"daily_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> daily_id
    {
      get { return _daily_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _daily_num = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(125, Name=@"daily_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> daily_num
    {
      get { return _daily_num; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _daily_reward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(126, Name=@"daily_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> daily_reward
    {
      get { return _daily_reward; }
    }
  
    private int _daily_point = default(int);
    [global::ProtoBuf.ProtoMember(127, IsRequired = false, Name=@"daily_point", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int daily_point
    {
      get { return _daily_point; }
      set { _daily_point = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _daily_get_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(128, Name=@"daily_get_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> daily_get_id
    {
      get { return _daily_get_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _level_reward = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(129, Name=@"level_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> level_reward
    {
      get { return _level_reward; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _social_golds = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(130, Name=@"social_golds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> social_golds
    {
      get { return _social_golds; }
    }
  
    private int _total_recharge = default(int);
    [global::ProtoBuf.ProtoMember(301, IsRequired = false, Name=@"total_recharge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_recharge
    {
      get { return _total_recharge; }
      set { _total_recharge = value; }
    }
    private int _total_spend = default(int);
    [global::ProtoBuf.ProtoMember(302, IsRequired = false, Name=@"total_spend", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int total_spend
    {
      get { return _total_spend; }
      set { _total_spend = value; }
    }
    private int _change_name_num = default(int);
    [global::ProtoBuf.ProtoMember(303, IsRequired = false, Name=@"change_name_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int change_name_num
    {
      get { return _change_name_num; }
      set { _change_name_num = value; }
    }
    private int _fenxiang_num = default(int);
    [global::ProtoBuf.ProtoMember(304, IsRequired = false, Name=@"fenxiang_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fenxiang_num
    {
      get { return _fenxiang_num; }
      set { _fenxiang_num = value; }
    }
    private int _fenxiang_total_num = default(int);
    [global::ProtoBuf.ProtoMember(305, IsRequired = false, Name=@"fenxiang_total_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fenxiang_total_num
    {
      get { return _fenxiang_total_num; }
      set { _fenxiang_total_num = value; }
    }
    private int _fenxiang_state = default(int);
    [global::ProtoBuf.ProtoMember(306, IsRequired = false, Name=@"fenxiang_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fenxiang_state
    {
      get { return _fenxiang_state; }
      set { _fenxiang_state = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _libao_nums = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(307, Name=@"libao_nums", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> libao_nums
    {
      get { return _libao_nums; }
    }
  
    private int _battle_num = default(int);
    [global::ProtoBuf.ProtoMember(308, IsRequired = false, Name=@"battle_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battle_num
    {
      get { return _battle_num; }
      set { _battle_num = value; }
    }
    private ulong _offline_battle_time = default(ulong);
    [global::ProtoBuf.ProtoMember(309, IsRequired = false, Name=@"offline_battle_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong offline_battle_time
    {
      get { return _offline_battle_time; }
      set { _offline_battle_time = value; }
    }
    private int _first_recharge = default(int);
    [global::ProtoBuf.ProtoMember(310, IsRequired = false, Name=@"first_recharge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int first_recharge
    {
      get { return _first_recharge; }
      set { _first_recharge = value; }
    }
    private ulong _yue_time = default(ulong);
    [global::ProtoBuf.ProtoMember(311, IsRequired = false, Name=@"yue_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong yue_time
    {
      get { return _yue_time; }
      set { _yue_time = value; }
    }
    private int _yue_reward = default(int);
    [global::ProtoBuf.ProtoMember(312, IsRequired = false, Name=@"yue_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yue_reward
    {
      get { return _yue_reward; }
      set { _yue_reward = value; }
    }
    private int _yue_first = default(int);
    [global::ProtoBuf.ProtoMember(313, IsRequired = false, Name=@"yue_first", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yue_first
    {
      get { return _yue_first; }
      set { _yue_first = value; }
    }
    private ulong _nian_time = default(ulong);
    [global::ProtoBuf.ProtoMember(314, IsRequired = false, Name=@"nian_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong nian_time
    {
      get { return _nian_time; }
      set { _nian_time = value; }
    }
    private int _nian_reward = default(int);
    [global::ProtoBuf.ProtoMember(315, IsRequired = false, Name=@"nian_reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nian_reward
    {
      get { return _nian_reward; }
      set { _nian_reward = value; }
    }
    private int _nian_first = default(int);
    [global::ProtoBuf.ProtoMember(316, IsRequired = false, Name=@"nian_first", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nian_first
    {
      get { return _nian_first; }
      set { _nian_first = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _duobao_items = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(317, Name=@"duobao_items", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> duobao_items
    {
      get { return _duobao_items; }
    }
  
    private int _duobao_num = default(int);
    [global::ProtoBuf.ProtoMember(318, IsRequired = false, Name=@"duobao_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int duobao_num
    {
      get { return _duobao_num; }
      set { _duobao_num = value; }
    }
    private int _advertisement_num = default(int);
    [global::ProtoBuf.ProtoMember(319, IsRequired = false, Name=@"advertisement_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int advertisement_num
    {
      get { return _advertisement_num; }
      set { _advertisement_num = value; }
    }
    private ulong _advertisement_time = default(ulong);
    [global::ProtoBuf.ProtoMember(320, IsRequired = false, Name=@"advertisement_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong advertisement_time
    {
      get { return _advertisement_time; }
      set { _advertisement_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}