#ifndef __OPCODES_H__
#define __OPCODES_H__


enum opself_t
{
	BEG_SELF_MESSAGE		= 0,

	END_SELF_MESSAGE		= 9999,
};

enum oppush_t
{
	BEG_PUSH_MESSAGE		= 10000,

	PUSH_GATE_CONNECT_PLAYER_NUM,
	PUSH_GATE_HALL_LOGOUT,
	PUSH_RC_RM_SET_PLAYER_ROOM,
	PUSH_RM_RC_BATTLE_END,
	PUSH_R_RM_CREATED,
	PUSH_RC_HALL_BATTLE_END,
	PUSH_HALL_CENTER_CHAT_HORN,
	PUSH_PIPE_CENTER_GONGGAO,
	PUSH_PIPE_CENTER_RECHARGE_ALI,
	PUSH_TEAM_HALL_ERROR,
	PUSH_HALL_TEAM_CREATE,
	PUSH_TEAM_HALL_CREATE,
	PUSH_HALL_TEAM_JOIN,
	PUSH_TEAM_HALL_JOIN,
	PUSH_TEAM_HALL_OTHER_JOIN,
	PUSH_HALL_TEAM_EXIT,
	PUSH_TEAM_HALL_EXIT,
	PUSH_HALL_TEAM_KICK,
	PUSH_TEAM_HALL_KICK,
	PUSH_HALL_TEAM_INVERT,
	PUSH_TEAM_HALL_INVERT,
	PUSH_HALL_TEAM_CHAT,
	PUSH_TEAM_HALL_CHAT,
	PUSH_HALL_TEAM_MULTI_BATTLE,
	PUSH_TEAM_HALL_MULTI_BATTLE,
	PUSH_HALL_NAME_INSERT,
	PUSH_PIPE_CENTER_RECHARGE_SIMULATION,
	PUSH_HALL_RANK_UPDATE,
	PUSH_RANK_HALL_CACHE,
	PUSH_HALL_RANK_FORBIDDEN,
	PUSH_PIPE_CENTER_RANK_FORBIDDEN,

	PUSH_SOCIAL_CHAT = 10100,
	PUSH_SOCIAL_GIFT,
	PUSH_SOCIAL_REJECT,
	PUSH_SOCIAL_LOGOUT,
	PUSH_SOCIAL_DELETE,
	PUSH_SOCIAL_ADD,
	PUSH_SOCIAL_APPLY,
	PUSH_SOCIAL_LOGIN,
	PUSH_SOCIAL_FIGHT,

	END_PUSH_MESSAGE		= 19999,
};

enum opreq_t
{
	BEG_REQ_MESSAGE			= 20000,

	REQ_HALL_RC_SINGLE_BATTLE,
	REQ_RC_RM_CREATE_ROOM,
	REQ_HALL_CENTER_PLAYER_LOOK,
	REQ_CENTER_HALL_PLAYER_LOOK,
	REQ_HALL_CENTER_LIBAO,
	REQ_HALL_CENTER_RECHARGE,
	REQ_HALL_RC_HAS_BATTLE,
	REQ_LOGIN,
	REQ_TEAM_RC_MULTI_BATTLE,
	REQ_SOCIAL_NAME_SEARCH,

	REQ_SOCIAL_ADD = 20100,
	REQ_SOCIAL_APPLY,
	REQ_SOCIAL_BLACK,
	REQ_SOCIAL_LOGIN,
	REQ_SOCIAL_DELETE,
	REQ_SOCIAL_LOOK,
	REQ_SOCIAL_REJECT,
	REQ_SOICAL_GOLD,
	REQ_SOCIAL_GIFT,
	
	END_REQ_MESSAGE			= 29999,
};

enum opclient_t
{
	BEG_CLIENT_MESSAGE = 30000,

	/// 系统通用
	CMSG_ENTER_WORLD,
	CMSG_LEAVE_WORLD,
	CMSG_ENTER_WORLD_UDP,
	CMSG_LEAVE_WORLD_UDP,
	/// connect
	CMSG_REQUEST_GATE = 30100,
	/// 登陆
	CMSG_LOGIN = 30200,
	CMSG_LOGIN_PLAYER,
	CMSG_RELOGIN_PLAYER,
	CMSG_BEAT,
	/// 对战
	CMSG_SINGLE_BATTLE = 30300,
	CMSG_BATTLE_LINK,
	CMSG_BATTLE_IN,
	CMSG_BATTLE_STATE,
	CMSG_BATTLE_RESET,
	CMSG_BATTLE_OP,
	CMSG_BATTLE_END,
	CMSG_OFFLINE_BATTLE,
	CMSG_OFFLINE_BATTLE_END,
	CMSG_TEAM_CREATE,
	CMSG_TEAM_TUIJIAN,
	CMSG_TEAM_JOIN,
	CMSG_TEAM_EXIT,
	CMSG_TEAM_KICK,
	CMSG_TEAM_INVERT,
	CMSG_TEAM_CHAT,
	CMSG_MULTI_BATTLE,
	CMSG_BATTLE_CODE,
	/// 系統
	CMSG_ITEM_SELL = 30400,
	CMSG_ITEM_DIRECT_BUY,
	CMSG_GM_COMMAND,
	CMSG_PLAYER_LOOK,
	CMSG_CHAT_CHANNEL,
	CMSG_AVATAR_ON,
	CMSG_ROLE_ON,
	CMSG_ROLE_HECHENG,
	CMSG_ROLE_LEVELUP,
	CMSG_CHANGE_NAME,
	CMSG_MODIFY_DATA,
	CMSG_START_OPEN_BOX,
	CMSG_END_OPEN_BOX,
	CMSG_ITEM_BUY,
	CMSG_POST_LOOK,
	CMSG_POST_READ,
	CMSG_POST_GET,
	CMSG_POST_DELETE,
	CMSG_POST_GET_ALL,
	CMSG_POST_DELETE_ALL,
	CMSG_OPEN_BATTLE_BOX,
	CMSG_SIGN,
	CMSG_LIBAO,
	CMSG_RECHARGE,
	CMSG_CHECKDATA,
	CMSG_FENXIANG,
	CMSG_OPEN_FENXIANG_BOX,
	CMSG_TOUKUANG_ON,
	CMSG_INFOMATION,
	CMSG_ITEM_APPLY,
	CMSG_BATTLE_ACHIEVE,
	CMSG_ACHIEVE,
	CMSG_ACHIEVE_REWARD,
	CMSG_GUIDE,
	CMSG_BATTLE_TASK,
	CMSG_TASK,
	CMSG_BATTLE_DAILY,
	CMSG_DAILY,
	CMSG_DAILY_REWARD,
	CMSG_FASHION_ON,
	CMSG_LEVEL_REWARD,
	CMSG_VIP_REWARD,
	CMSG_DUOBAO,
	CMSG_RANK,
	CMSG_ADVERTISEMENT,

	CMSG_SOCIAL_LOOK,
	CMSG_SOCIAL_DELETE,
	CMSG_SOCIAL_APPLY,
	CMSG_SOCIAL_APPLY_REJECT,
	CMSG_SOCIAL_ADD,
	CMSG_SOCIAL_BLACK,
	CMSG_SOCIAL_GIFT,
	CMSG_SOCIAL_CHAT,
	CMSG_SOCIAL_GIFT_GET,
	CMSG_SOCIAL_TUIJIAN,
	CMSG_SOCIAL_SEARCH,
	CMSG_SOCIAL_LEAVE,

	END_CLIENT_MESSAGE		= 39999,
};

enum opserver_t
{
	BEG_SERVER_MESSAGE		= 40000,

	/// 系统通用
	SMSG_ERROR,
	/// connect
	SMSG_REQUEST_GATE		= 40100,
	/// 登陆
	SMSG_LOGIN				= 40200,
	SMSG_LOGIN_PLAYER,
	SMSG_BEAT,
	/// 对战
	SMSG_SINGLE_BATTLE		= 40300,
	SMSG_BATTLE_END,
	SMSG_BATTLE_LINK,
	SMSG_BATTLE_OP,
	SMSG_BATTLE_ZHEN,
	SMSG_HAS_BATTLE,
	SMSG_BATTLE_FINISH,
	SMSG_OFFLINE_BATTLE_END,
	SMSG_TEAM_CREATE,
	SMSG_TEAM_TUIJIAN,
	SMSG_TEAM_JOIN,
	SMSG_TEAM_OTHER_JOIN,
	SMSG_TEAM_EXIT,
	SMSG_TEAM_KICK,
	SMSG_TEAM_INVERT,
	SMSG_TEAM_CHAT,
	SMSG_MULTI_BATTLE,
	/// 系統
	SMSG_ITEM_SELL			= 40400,
	SMSG_ITEM_DIRECT_BUY,
	SMSG_GM_COMMAND,
	SMSG_PLAYER_LOOK,
	SMSG_CHAT,
	SMSG_CHAT_LABA,
	SMSG_GONGGAO,
	SMSG_AVATAR_ON,
	SMSG_ROLE_ON,
	SMSG_ROLE_HECHENG,
	SMSG_ROLE_LEVELUP,
	SMSG_CHANGE_NAME,
	SMSG_MODIFY_DATA,
	SMSG_START_OPEN_BOX,
	SMSG_END_OPEN_BOX,
	SMSG_BATTLE_ITEM_ON,
	SMSG_ITEM_BUY_BOX,
	SMSG_ITEM_BUY,
	SMSG_POST_LOOK,
	SMSG_POST_READ,
	SMSG_POST_GET,
	SMSG_POST_DELETE,
	SMSG_POST_GET_ALL,
	SMSG_POST_DELETE_ALL,
	SMSG_FENXIANG_NUM,
	SMSG_OPEN_BATTLE_BOX,
	SMSG_SIGN,
	SMSG_LIBAO,
	SMSG_RECHARGE,
	SMSG_CHECKDATA,
	SMSG_FENXIANG,
	SMSG_OPEN_FENXIANG_BOX,
	SMSG_TOUKUANG_ON,
	SMSG_INFOMATION,
	SMSG_ITEM_APPLY,
	SMSG_BATTLE_ACHIEVE,
	SMSG_ACHIEVE,
	SMSG_ACHIEVE_REWARD,
	SMSG_POST_NUM,
	SMSG_GUIDE,
	SMSG_LEVEL_REWARD,
	SMSG_BATTLE_TASK,
	SMSG_TASK,
	SMSG_FASHION_ON,
	SMSG_BATTLE_DAILY,
	SMSG_DAILY,
	SMSG_DAILY_REWARD,
	SMSG_VIP_REWARD,
	SMSG_DUOBAO,
	SMSG_SYS_INFO,
	SMSG_RANK,
	SMSG_ADVERTISEMENT,

	/// 好友
	SMSG_SOCAIL_LOOK = 40500,
	SMSG_SOCIAL_APPLY,
	SMSG_SOCIAL_APPLY_FLAG,
	SMSG_SOCIAL_ADD,
	SMSG_SOCIAL_BLACK,
	SMSG_SOCIAL_GIFT,
	SMSG_SOCIAL_DELETE,
	SMSG_SOCIAL_GIFT_GET,
	SMSG_SOCIAL_GIFT_PUSH,
	SMSG_SOCIAL_CHAT,
	SMSG_SOCIAL_GIFT_RECEIVE,
	SMSG_SOCIAL_APPLY_RECEIVE,
	SMSG_SOCIAL_DATA,
	SMSG_SOCIAL_STAT,
	SMSG_SOCIAL_TUIJIAN,
	SMSG_SOCIAL_SEARCH,
	SMSG_SOCIAL_GOLD,

	END_SERVER_MESSAGE		= 49999,
};

enum operror_t
{
	BEG_ERROR_MESSAGE		= 50000,

	/// 系统错误
	ERROR_SYSTEM,
	/// 不存在的gate
	ERROR_EMPTY_GATE,
	/// 账号停封
	ERROR_FENGHAO,
	/// 用户名密码错误
	ERROR_ACCOUNT_PASSWORD,
	/// 用户已存在
	ERROR_ACCOUNT_EXSIT,
	/// 已经断开连接
	ERROR_DISCONNECTED,
	/// 账号在别处登陆
	ERROR_LOGIN_OTHER,
	/// 聊天间隔
	ERROR_CHAT_INTERVAL,
	/// 非法字符
	ERROR_NAME_ILL,
	/// 登录已过期
	ERROR_LOGIN_CODE,
	/// 没有该礼包码
	ERROR_LIBAO_NO,
	/// 非本平台的礼包码
	ERROR_LIBAO_PT,
	/// 礼包码已被使用
	ERROR_LIBAO_USED,
	/// 该类礼包领取次数达到上限
	ERROR_LIBAO_NUM,
	/// 充值错误
	ERROR_RECHARGE,

	/// 对方好友数量已达上限，添加好友失败
	ERROR_SOCIAL_FULL		= 50100,
	/// 您的好友数量已达上限，请删除部分好友再操作
	ERROR_SOCIAL_FRIEND_FULL,
	/// 黑名单数量已达上限
	ERROR_SOCIAL_BLACK_FULL,
	/// 重复向对方发送验证消息
	ERROR_SOCIAL_APPLY,
	/// 对方拒绝加好友
	ERROR_SOCIAL_REJECT,
	/// 玩家拒绝加好友
	ERROR_SOCIAL_BLACK,
	ERROR_SOCIAL_FRIEND,
	ERROR_SOCIAL_VERIFY,
	ERROR_SOCIAL_ADD,
	ERROR_SOCIAL_GIFT_NUM,

	ERROR_TEAM_EXIST		= 50200,
	ERROR_TEAM_NOT_EXIST,
	ERROR_TEAM_FULL,
	ERROR_TEAM_MEMBER_DUMP,
	ERROR_TEAM_MEMBER_NOT_IN,
	ERROR_TEAM_MEMBER_NOT_LEADER,
	ERROR_TEAM_MEMBER_OTHER_NOT_IN,
	ERROR_TEAM_MEMBER_OTHER_DUMP,

	END_ERROR_MESSAGE		= 59999,
};

#endif
