#ifndef __PROTOCOL_INC_H__
#define __PROTOCOL_INC_H__

#include "opcodes.h"
#include "../../../common/protocpp/acc.pb.h"
#include "../../../common/protocpp/gtool.pb.h"
#include "../../../common/protocpp/player.pb.h"
#include "../../../common/protocpp/role.pb.h"
#include "../../../common/protocpp/battle_his.pb.h"
#include "../../../common/protocpp/battle_result.pb.h"
#include "../../../common/protocpp/msg_pipe.pb.h"
#include "../../../common/protocpp/msg_connect.pb.h"
#include "../../../common/protocpp/msg_login.pb.h"
#include "../../../common/protocpp/msg_hall.pb.h"
#include "../../../common/protocpp/msg_hall1.pb.h"
#include "../../../common/protocpp/msg_battle.pb.h"
#include "../../../common/protocpp/msg_battle1.pb.h"
#include "../../../common/protocpp/msg_team.pb.h"
#include "../../../common/protocpp/post.pb.h"
#include "../../../common/protocpp/post_new.pb.h"
#include "../../../common/protocpp/share.pb.h"
#include "../../../common/protocpp/recharge.pb.h"
#include "../../../common/protocpp/social.pb.h"
#include "../../../common/protocpp/msg_social.pb.h"
#include "../../../common/protocpp/social_list.pb.h"
#include "../../../common/protocpp/name.pb.h"
#include "../../../common/protocpp/msg_name.pb.h"
#include "../../../common/protocpp/rank.pb.h"
#include "../../../common/protocpp/msg_rank.pb.h"

#endif
